"""add_platform_post_id

Revision ID: e6638ef4adeb
Revises: c50fd7a84c62
Create Date: 2026-08-11 16:13:27.647175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6638ef4adeb'
down_revision: Union[str, None] = 'c50fd7a84c62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
