"""add platform_post_id to posts

Revision ID: c50fd7a84c62
Revises: a3f1c2d4e5b6
Create Date: 2026-08-11 16:03:25.478069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c50fd7a84c62'
down_revision: Union[str, None] = 'a3f1c2d4e5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_campaign_posts_campaign', table_name='campaign_posts')
    op.drop_index('idx_campaign_posts_post', table_name='campaign_posts')
    op.create_index(op.f('ix_campaign_posts_campaign_id'), 'campaign_posts', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_posts_id'), 'campaign_posts', ['id'], unique=False)
    op.create_index(op.f('ix_campaign_posts_post_id'), 'campaign_posts', ['post_id'], unique=False)
    op.add_column('posts', sa.Column('platform_post_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_posts_platform_post_id'), 'posts', ['platform_post_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_platform_post_id'), table_name='posts')
    op.drop_column('posts', 'platform_post_id')
    op.drop_index(op.f('ix_campaign_posts_post_id'), table_name='campaign_posts')
    op.drop_index(op.f('ix_campaign_posts_id'), table_name='campaign_posts')
    op.drop_index(op.f('ix_campaign_posts_campaign_id'), table_name='campaign_posts')
    op.create_index('idx_campaign_posts_post', 'campaign_posts', ['post_id'], unique=False)
    op.create_index('idx_campaign_posts_campaign', 'campaign_posts', ['campaign_id'], unique=False)
    # ### end Alembic commands ###
