"""add_posts_scheduled_posts_queue

Revision ID: d186be4742b6
Revises: 9840678fc460
Create Date: 2026-07-21 20:34:23.398906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd186be4742b6'
down_revision: Union[str, None] = '9840678fc460'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
